project:
  type: book
  output-dir: docs

book:
  title: "The Mini Buoy Handbook"
  subtitle: 'Assessing hydrodynamics in intertidal environments'
  author: 
    - Cai Ladd
    - Alejandra Vovides
    - Marie-Christin Wimmler
    - Christian Schwarz
    - Thorsten Balke
    
  date: "06/01/2024"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/assembly.qmd
    - chapters/configuration.qmd
    - chapters/deployment.qmd
    - chapters/export.qmd
    - chapters/analysis.qmd
    - references.qmd
  cover-image: Cover.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    